# roles/dnsmasq/tasks/main.yml
---
- name: Install Dnsmasq
  package:
    name: dnsmasq
    state: present
  tags: dnsmasq

- name: Set configuration file
  template:
    src: etc_dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    validate: 'dnsmasq --test --conf-file=%s'
  notify: restart dnsmasq
  tags: dnsmasq

- name: Make sure Dnsmasq is running
  service:
    name: dnsmasq
    state: started
    enabled: yes
  tags: dnsmasq

- name: Enable FirewallD DNS service
  firewalld:
    service: dns
    zone: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  notify:
    - restart firewalld
  with_items: "{{ firewalld_dns_zones | default([]) }}"
  when: firewalld_dns_zones is defined
  tags: dnsmasq
